version: '3.3'

services:
  redis-server:
    image: redis:latest
    container_name: redis-server
    ports:
      - 6379:6379
    restart: always
    volumes:
      - ../volumes/redis_data:/var/lib/redis_data/data
      - ../redis.conf:/usr/local/etc/redis/redis.conf

    command: ['/usr/local/etc/redis/redis.conf']
    networks:
      - my-network
    healthcheck:
      test:
        [
          'CMD-SHELL',
          "sh -c 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}'",
        ]
      interval: 5s
      timeout: 5s
      retries: 10
