version: '3.3'

services:
  # frontend:
  #   container_name: frontend
  #   build:
  #     context: ../
  #     dockerfile: ./apps/group-chat/Dockerfile
  #   #   args:
  #   #     BACKEND_API: 'http://gateway:3000/api'
  #   # environment:
  #   #   - BACKEND_API=http://gatedadadadway:3000/api
  #   ports:
  #     - '4200:80'
  #   # depends_on:
  #   #   - gateway
  #   networks:
  #     - my-network

  # web:
  #   extends:
  #     file: templates/angular_app.yml
  #     service: frontend

  # gateway:
  #   extends:
  #     file: templates/gateway.yml
  #     service: gateway
  db:
    extends:
      file: templates/postgress.yml
      service: Postgres-Server
  redis:
    extends:
      file: templates/redis.yml
      service: redis-server

networks:
  my-network:
    driver: bridge
